package edsdk.bindings;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : EDSDK/Header/EDSDKTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EdsPictureStyleDesc extends Structure {
	/** C type : EdsInt32 */
	public NativeLong contrast;
	/** C type : EdsUInt32 */
	public NativeLong sharpness;
	/** C type : EdsInt32 */
	public NativeLong saturation;
	/** C type : EdsInt32 */
	public NativeLong colorTone;
	/** C type : EdsUInt32 */
	public NativeLong filterEffect;
	/** C type : EdsUInt32 */
	public NativeLong toningEffect;
	/** C type : EdsUInt32 */
	public NativeLong sharpFineness;
	/** C type : EdsUInt32 */
	public NativeLong sharpThreshold;
	public EdsPictureStyleDesc() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("contrast", "sharpness", "saturation", "colorTone", "filterEffect", "toningEffect", "sharpFineness", "sharpThreshold");
	}
	/**
	 * @param contrast C type : EdsInt32<br>
	 * @param sharpness C type : EdsUInt32<br>
	 * @param saturation C type : EdsInt32<br>
	 * @param colorTone C type : EdsInt32<br>
	 * @param filterEffect C type : EdsUInt32<br>
	 * @param toningEffect C type : EdsUInt32<br>
	 * @param sharpFineness C type : EdsUInt32<br>
	 * @param sharpThreshold C type : EdsUInt32
	 */
	public EdsPictureStyleDesc(NativeLong contrast, NativeLong sharpness, NativeLong saturation, NativeLong colorTone, NativeLong filterEffect, NativeLong toningEffect, NativeLong sharpFineness, NativeLong sharpThreshold) {
		super();
		this.contrast = contrast;
		this.sharpness = sharpness;
		this.saturation = saturation;
		this.colorTone = colorTone;
		this.filterEffect = filterEffect;
		this.toningEffect = toningEffect;
		this.sharpFineness = sharpFineness;
		this.sharpThreshold = sharpThreshold;
	}
	public EdsPictureStyleDesc(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends EdsPictureStyleDesc implements Structure.ByReference {
		
	};
	public static class ByValue extends EdsPictureStyleDesc implements Structure.ByValue {
		
	};
}
