package edsdk.bindings;

import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : EDSDK\Header\EDSDKTypes.h</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class EdsSize extends Structure {

    /// C type : EdsInt32
    public NativeLong width;
    /// C type : EdsInt32
    public NativeLong height;

    public EdsSize() {
        super();
        initFieldOrder();
    }

    protected void initFieldOrder() {
        setFieldOrder( new String[] { "width", "height" } );
    }

    /**
     * @param width C type : EdsInt32<br>
     * @param height C type : EdsInt32
     */
    public EdsSize( final NativeLong width, final NativeLong height ) {
        super();
        this.width = width;
        this.height = height;
        initFieldOrder();
    }

    public EdsSize( final Pointer pointer ) {
        super( pointer );
        read();
    }

    public static class ByReference extends EdsSize implements Structure.ByReference {

    };

    public static class ByValue extends EdsSize implements Structure.ByValue {

    };
}
