package add;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>add</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("add") 
@Runtime(CRuntime.class) 
public class AddLibrary {
	static {
		BridJ.register();
	}
	/**
	 * function declarations<br>
	 * Original signature : <code>int addNumber(int, int)</code><br>
	 * <i>native declaration : add.h:2</i>
	 */
	public static native int addNumber(int a, int b);
}
