package edsdk;
import java.io.File;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;

import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.NativeLongByReference;
import com.sun.jna.ptr.PointerByReference;
import com.sun.jna.ptr.ShortByReference;
import com.sun.jna.win32.StdCallLibrary;
import com.sun.jna.win32.StdCallLibrary.StdCallCallback;

import edsdk.utils.CanonUtils;
/**
 * JNA Wrapper for library <b>test</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface CanonSDK extends StdCallLibrary{
	//public static final java.lang.String JNA_LIBRARY_NAME = LibraryExtractor.getLibraryPath("EDSDK", true, edsdk.CanonSDK.class);
	//public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(edsdk.CanonSDK.JNA_LIBRARY_NAME, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	//public static final CanonSDK INSTANCE = (CanonSDK)Native.loadLibrary(edsdk.CanonSDK.JNA_LIBRARY_NAME, edsdk.CanonSDK.class, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
//	public static final CanonSDK INSTANCE = (CanonSDK) Native.loadLibrary("dll/EDSDK.dll", CanonSDK.class );
	
	public static final CanonSDK INSTANCE = 
			System.getProperty( "os.name" ).toLowerCase().contains( "windows" )? 
			(CanonSDK) Native.loadLibrary("dll/EDSDK.dll", CanonSDK.class ) : 
			(CanonSDK) Native.loadLibrary( new File( "/Library/Frameworks/EDSDK.framework/EDSDK" ).getAbsolutePath(), CanonSDK.class );
	
			
			static float x = CanonUtils.abc( "initialize canonsdk / load dll" ); 
				; 
	/// enum values
	public static interface EdsDataType {
		/// <i>native declaration : line 344</i>
		public static final int kEdsDataType_Unknown = 0;
		/// <i>native declaration : line 345</i>
		public static final int kEdsDataType_Bool = 1;
		/// <i>native declaration : line 346</i>
		public static final int kEdsDataType_String = 2;
		/// <i>native declaration : line 347</i>
		public static final int kEdsDataType_Int8 = 3;
		/// <i>native declaration : line 348</i>
		public static final int kEdsDataType_UInt8 = 6;
		/// <i>native declaration : line 349</i>
		public static final int kEdsDataType_Int16 = 4;
		/// <i>native declaration : line 350</i>
		public static final int kEdsDataType_UInt16 = 7;
		/// <i>native declaration : line 351</i>
		public static final int kEdsDataType_Int32 = 8;
		/// <i>native declaration : line 352</i>
		public static final int kEdsDataType_UInt32 = 9;
		/// <i>native declaration : line 353</i>
		public static final int kEdsDataType_Int64 = 10;
		/// <i>native declaration : line 354</i>
		public static final int kEdsDataType_UInt64 = 11;
		/// <i>native declaration : line 355</i>
		public static final int kEdsDataType_Float = 12;
		/// <i>native declaration : line 356</i>
		public static final int kEdsDataType_Double = 13;
		/// <i>native declaration : line 357</i>
		public static final int kEdsDataType_ByteBlock = 14;
		/// <i>native declaration : line 358</i>
		public static final int kEdsDataType_Rational = 20;
		/// <i>native declaration : line 359</i>
		public static final int kEdsDataType_Point = 21;
		/// <i>native declaration : line 360</i>
		public static final int kEdsDataType_Rect = 22;
		/// <i>native declaration : line 361</i>
		public static final int kEdsDataType_Time = 23;
		/// <i>native declaration : line 363</i>
		public static final int kEdsDataType_Bool_Array = 30;
		/// <i>native declaration : line 364</i>
		public static final int kEdsDataType_Int8_Array = 31;
		/// <i>native declaration : line 365</i>
		public static final int kEdsDataType_Int16_Array = 32;
		/// <i>native declaration : line 366</i>
		public static final int kEdsDataType_Int32_Array = 33;
		/// <i>native declaration : line 367</i>
		public static final int kEdsDataType_UInt8_Array = 34;
		/// <i>native declaration : line 368</i>
		public static final int kEdsDataType_UInt16_Array = 35;
		/// <i>native declaration : line 369</i>
		public static final int kEdsDataType_UInt32_Array = 36;
		/// <i>native declaration : line 370</i>
		public static final int kEdsDataType_Rational_Array = 37;
		/// <i>native declaration : line 372</i>
		public static final int kEdsDataType_FocusInfo = 101;
		/// <i>native declaration : line 373</i>
		public static final int kEdsDataType_PictureStyleDesc = 102;
	};
	/// enum values
	public static interface EdsEvfAf {
		/// <i>native declaration : line 535</i>
		public static final int kEdsCameraCommand_EvfAf_OFF = 0;
		/// <i>native declaration : line 536</i>
		public static final int kEdsCameraCommand_EvfAf_ON = 1;
	};
	/// enum values
	public static interface EdsShutterButton {
		/// <i>native declaration : line 541</i>
		public static final int kEdsCameraCommand_ShutterButton_OFF = 0;
		/// <i>native declaration : line 542</i>
		public static final int kEdsCameraCommand_ShutterButton_Halfway = 1;
		/// <i>native declaration : line 543</i>
		public static final int kEdsCameraCommand_ShutterButton_Completely = 3;
		/// <i>native declaration : line 544</i>
		public static final int kEdsCameraCommand_ShutterButton_Halfway_NonAF = 65537;
		/// <i>native declaration : line 545</i>
		public static final int kEdsCameraCommand_ShutterButton_Completely_NonAF = 65539;
	};
	/// enum values
	public static interface EdsEvfDriveLens {
		/// <i>native declaration : line 747</i>
		public static final int kEdsEvfDriveLens_Near1 = 1;
		/// <i>native declaration : line 748</i>
		public static final int kEdsEvfDriveLens_Near2 = 2;
		/// <i>native declaration : line 749</i>
		public static final int kEdsEvfDriveLens_Near3 = 3;
		/// <i>native declaration : line 750</i>
		public static final int kEdsEvfDriveLens_Far1 = 32769;
		/// <i>native declaration : line 751</i>
		public static final int kEdsEvfDriveLens_Far2 = 32770;
		/// <i>native declaration : line 752</i>
		public static final int kEdsEvfDriveLens_Far3 = 32771;
	};
	/// enum values
	public static interface EdsEvfDepthOfFieldPreview {
		/// <i>native declaration : line 761</i>
		public static final int kEdsEvfDepthOfFieldPreview_OFF = 0;
		/// <i>native declaration : line 762</i>
		public static final int kEdsEvfDepthOfFieldPreview_ON = 1;
	};
	/// enum values
	public static interface EdsSeekOrigin {
		/// <i>native declaration : line 771</i>
		public static final int kEdsSeek_Cur = 0;
		/// <i>native declaration : line 772</i>
		public static final int kEdsSeek_Begin = 1;
		/// <i>native declaration : line 773</i>
		public static final int kEdsSeek_End = 2;
	};
	/// enum values
	public static interface EdsAccess {
		/// <i>native declaration : line 782</i>
		public static final int kEdsAccess_Read = 0;
		/// <i>native declaration : line 783</i>
		public static final int kEdsAccess_Write = 1;
		/// <i>native declaration : line 784</i>
		public static final int kEdsAccess_ReadWrite = 2;
		/// <i>native declaration : line 785</i>
		public static final int kEdsAccess_Error = -1;
	};
	/// enum values
	public static interface EdsFileCreateDisposition {
		/// <i>native declaration : line 794</i>
		public static final int kEdsFileCreateDisposition_CreateNew = 0;
		/// <i>native declaration : line 795</i>
		public static final int kEdsFileCreateDisposition_CreateAlways = 1;
		/// <i>native declaration : line 796</i>
		public static final int kEdsFileCreateDisposition_OpenExisting = 2;
		/// <i>native declaration : line 797</i>
		public static final int kEdsFileCreateDisposition_OpenAlways = 3;
		/// <i>native declaration : line 798</i>
		public static final int kEdsFileCreateDisposition_TruncateExsisting = 4;
	};
	/// enum values
	public static interface EdsImageType {
		/// <i>native declaration : line 809</i>
		public static final int kEdsImageType_Unknown = 0;
		/// <i>native declaration : line 810</i>
		public static final int kEdsImageType_Jpeg = 1;
		/// <i>native declaration : line 811</i>
		public static final int kEdsImageType_CRW = 2;
		/// <i>native declaration : line 812</i>
		public static final int kEdsImageType_RAW = 4;
		/// <i>native declaration : line 813</i>
		public static final int kEdsImageType_CR2 = 6;
	};
	/// enum values
	public static interface EdsImageSize {
		/// <i>native declaration : line 822</i>
		public static final int kEdsImageSize_Large = 0;
		/// <i>native declaration : line 823</i>
		public static final int kEdsImageSize_Middle = 1;
		/// <i>native declaration : line 824</i>
		public static final int kEdsImageSize_Small = 2;
		/// <i>native declaration : line 825</i>
		public static final int kEdsImageSize_Middle1 = 5;
		/// <i>native declaration : line 826</i>
		public static final int kEdsImageSize_Middle2 = 6;
		/// <i>native declaration : line 827</i>
		public static final int kEdsImageSize_Unknown = -1;
	};
	/// enum values
	public static interface EdsCompressQuality {
		/// <i>native declaration : line 836</i>
		public static final int kEdsCompressQuality_Normal = 2;
		/// <i>native declaration : line 837</i>
		public static final int kEdsCompressQuality_Fine = 3;
		/// <i>native declaration : line 838</i>
		public static final int kEdsCompressQuality_Lossless = 4;
		/// <i>native declaration : line 839</i>
		public static final int kEdsCompressQuality_SuperFine = 5;
		/// <i>native declaration : line 840</i>
		public static final int kEdsCompressQuality_Unknown = -1;
	};
	/// enum values
	public static interface EdsImageSource {
		/// <i>native declaration : line 849</i>
		public static final int kEdsImageSrc_FullView = 0;
		/// <i>native declaration : line 850</i>
		public static final int kEdsImageSrc_Thumbnail = 1;
		/// <i>native declaration : line 851</i>
		public static final int kEdsImageSrc_Preview = 2;
		/// <i>native declaration : line 852</i>
		public static final int kEdsImageSrc_RAWThumbnail = 3;
		/// <i>native declaration : line 853</i>
		public static final int kEdsImageSrc_RAWFullView = 4;
	};
	/// enum values
	public static interface EdsTargetImageType {
		/// <i>native declaration : line 863</i>
		public static final int kEdsTargetImageType_Unknown = 0;
		/// <i>native declaration : line 864</i>
		public static final int kEdsTargetImageType_Jpeg = 1;
		/// <i>native declaration : line 865</i>
		public static final int kEdsTargetImageType_TIFF = 7;
		/// <i>native declaration : line 866</i>
		public static final int kEdsTargetImageType_TIFF16 = 8;
		/// <i>native declaration : line 867</i>
		public static final int kEdsTargetImageType_RGB = 9;
		/// <i>native declaration : line 868</i>
		public static final int kEdsTargetImageType_RGB16 = 10;
		/// <i>native declaration : line 869</i>
		public static final int kEdsTargetImageType_DIB = 11;
	};
	/// enum values
	public static interface EdsProgressOption {
		/// <i>native declaration : line 878</i>
		public static final int kEdsProgressOption_NoReport = 0;
		/// <i>native declaration : line 879</i>
		public static final int kEdsProgressOption_Done = 1;
		/// <i>native declaration : line 880</i>
		public static final int kEdsProgressOption_Periodically = 2;
	};
	/// enum values
	public static interface EdsFileAttributes {
		/// <i>native declaration : line 890</i>
		public static final int kEdsFileAttribute_Normal = 0;
		/// <i>native declaration : line 891</i>
		public static final int kEdsFileAttribute_ReadOnly = 1;
		/// <i>native declaration : line 892</i>
		public static final int kEdsFileAttribute_Hidden = 2;
		/// <i>native declaration : line 893</i>
		public static final int kEdsFileAttribute_System = 4;
		/// <i>native declaration : line 894</i>
		public static final int kEdsFileAttribute_Archive = 32;
	};
	/// enum values
	public static interface EdsBatteryLevel2 {
		/// <i>native declaration : line 904</i>
		public static final int kEdsBatteryLevel2_Empty = 0;
		/// <i>native declaration : line 905</i>
		public static final int kEdsBatteryLevel2_Low = 9;
		/// <i>native declaration : line 906</i>
		public static final int kEdsBatteryLevel2_Half = 49;
		/// <i>native declaration : line 907</i>
		public static final int kEdsBatteryLevel2_Normal = 80;
		/// <i>native declaration : line 908</i>
		public static final int kEdsBatteryLevel2_Hi = 69;
		/// <i>native declaration : line 909</i>
		public static final int kEdsBatteryLevel2_Quarter = 19;
		/// <i>native declaration : line 910</i>
		public static final int kEdsBatteryLevel2_Error = 0;
		/// <i>native declaration : line 911</i>
		public static final int kEdsBatteryLevel2_BCLevel = 0;
		/// <i>native declaration : line 912</i>
		public static final int kEdsBatteryLevel2_AC = -1;
	};
	/// enum values
	public static interface EdsSaveTo {
		/// <i>native declaration : line 920</i>
		public static final int kEdsSaveTo_Camera = 1;
		/// <i>native declaration : line 921</i>
		public static final int kEdsSaveTo_Host = 2;
		/// <i>native declaration : line 922</i>
		public static final int kEdsSaveTo_Both = CanonSDK.EdsSaveTo.kEdsSaveTo_Camera | CanonSDK.EdsSaveTo.kEdsSaveTo_Host;
	};
	/// enum values
	public static interface EdsStorageType {
		/// <i>native declaration : line 931</i>
		public static final int kEdsStorageType_Non = 0;
		/// <i>native declaration : line 932</i>
		public static final int kEdsStorageType_CF = 1;
		/// <i>native declaration : line 933</i>
		public static final int kEdsStorageType_SD = 2;
		/// <i>native declaration : line 934</i>
		public static final int kEdsStorageType_HD = 4;
	};
	/// enum values
	public static interface EdsWhiteBalance {
		/// <i>native declaration : line 943</i>
		public static final int kEdsWhiteBalance_Auto = 0;
		/// <i>native declaration : line 944</i>
		public static final int kEdsWhiteBalance_Daylight = 1;
		/// <i>native declaration : line 945</i>
		public static final int kEdsWhiteBalance_Cloudy = 2;
		/// <i>native declaration : line 946</i>
		public static final int kEdsWhiteBalance_Tangsten = 3;
		/// <i>native declaration : line 947</i>
		public static final int kEdsWhiteBalance_Fluorescent = 4;
		/// <i>native declaration : line 948</i>
		public static final int kEdsWhiteBalance_Strobe = 5;
		/// <i>native declaration : line 949</i>
		public static final int kEdsWhiteBalance_WhitePaper = 6;
		/// <i>native declaration : line 950</i>
		public static final int kEdsWhiteBalance_Shade = 8;
		/// <i>native declaration : line 951</i>
		public static final int kEdsWhiteBalance_ColorTemp = 9;
		/// <i>native declaration : line 952</i>
		public static final int kEdsWhiteBalance_PCSet1 = 10;
		/// <i>native declaration : line 953</i>
		public static final int kEdsWhiteBalance_PCSet2 = 11;
		/// <i>native declaration : line 954</i>
		public static final int kEdsWhiteBalance_PCSet3 = 12;
		/// <i>native declaration : line 955</i>
		public static final int kEdsWhiteBalance_WhitePaper2 = 15;
		/// <i>native declaration : line 956</i>
		public static final int kEdsWhiteBalance_WhitePaper3 = 16;
		/// <i>native declaration : line 957</i>
		public static final int kEdsWhiteBalance_WhitePaper4 = 18;
		/// <i>native declaration : line 958</i>
		public static final int kEdsWhiteBalance_WhitePaper5 = 19;
		/// <i>native declaration : line 959</i>
		public static final int kEdsWhiteBalance_PCSet4 = 20;
		/// <i>native declaration : line 960</i>
		public static final int kEdsWhiteBalance_PCSet5 = 21;
		/// <i>native declaration : line 961</i>
		public static final int kEdsWhiteBalance_Click = -1;
		/// <i>native declaration : line 962</i>
		public static final int kEdsWhiteBalance_Pasted = -2;
	};
	/// enum values
	public static interface EdsPhotoEffect {
		/// <i>native declaration : line 971</i>
		public static final int kEdsPhotoEffect_Off = 0;
		/// <i>native declaration : line 972</i>
		public static final int kEdsPhotoEffect_Monochrome = 5;
	};
	/// enum values
	public static interface EdsColorMatrix {
		/// <i>native declaration : line 981</i>
		public static final int kEdsColorMatrix_Custom = 0;
		/// <i>native declaration : line 982</i>
		public static final int kEdsColorMatrix_1 = 1;
		/// <i>native declaration : line 983</i>
		public static final int kEdsColorMatrix_2 = 2;
		/// <i>native declaration : line 984</i>
		public static final int kEdsColorMatrix_3 = 3;
		/// <i>native declaration : line 985</i>
		public static final int kEdsColorMatrix_4 = 4;
		/// <i>native declaration : line 986</i>
		public static final int kEdsColorMatrix_5 = 5;
		/// <i>native declaration : line 987</i>
		public static final int kEdsColorMatrix_6 = 6;
		/// <i>native declaration : line 988</i>
		public static final int kEdsColorMatrix_7 = 7;
	};
	/// enum values
	public static interface EdsFilterEffect {
		/// <i>native declaration : line 997</i>
		public static final int kEdsFilterEffect_None = 0;
		/// <i>native declaration : line 998</i>
		public static final int kEdsFilterEffect_Yellow = 1;
		/// <i>native declaration : line 999</i>
		public static final int kEdsFilterEffect_Orange = 2;
		/// <i>native declaration : line 1000</i>
		public static final int kEdsFilterEffect_Red = 3;
		/// <i>native declaration : line 1001</i>
		public static final int kEdsFilterEffect_Green = 4;
	};
	/// enum values
	public static interface EdsTonigEffect {
		/// <i>native declaration : line 1010</i>
		public static final int kEdsTonigEffect_None = 0;
		/// <i>native declaration : line 1011</i>
		public static final int kEdsTonigEffect_Sepia = 1;
		/// <i>native declaration : line 1012</i>
		public static final int kEdsTonigEffect_Blue = 2;
		/// <i>native declaration : line 1013</i>
		public static final int kEdsTonigEffect_Purple = 3;
		/// <i>native declaration : line 1014</i>
		public static final int kEdsTonigEffect_Green = 4;
	};
	/// enum values
	public static interface EdsColorSpace {
		/// <i>native declaration : line 1023</i>
		public static final int kEdsColorSpace_sRGB = 1;
		/// <i>native declaration : line 1024</i>
		public static final int kEdsColorSpace_AdobeRGB = 2;
		/// <i>native declaration : line 1025</i>
		public static final int kEdsColorSpace_Unknown = -1;
	};
	/// enum values
	public static interface EdsPictureStyle {
		/// <i>native declaration : line 1034</i>
		public static final int kEdsPictureStyle_Standard = 129;
		/// <i>native declaration : line 1035</i>
		public static final int kEdsPictureStyle_Portrait = 130;
		/// <i>native declaration : line 1036</i>
		public static final int kEdsPictureStyle_Landscape = 131;
		/// <i>native declaration : line 1037</i>
		public static final int kEdsPictureStyle_Neutral = 132;
		/// <i>native declaration : line 1038</i>
		public static final int kEdsPictureStyle_Faithful = 133;
		/// <i>native declaration : line 1039</i>
		public static final int kEdsPictureStyle_Monochrome = 134;
		/// <i>native declaration : line 1040</i>
		public static final int kEdsPictureStyle_User1 = 33;
		/// <i>native declaration : line 1041</i>
		public static final int kEdsPictureStyle_User2 = 34;
		/// <i>native declaration : line 1042</i>
		public static final int kEdsPictureStyle_User3 = 35;
		/// <i>native declaration : line 1043</i>
		public static final int kEdsPictureStyle_PC1 = 65;
		/// <i>native declaration : line 1044</i>
		public static final int kEdsPictureStyle_PC2 = 66;
		/// <i>native declaration : line 1045</i>
		public static final int kEdsPictureStyle_PC3 = 67;
	};
	/// enum values
	public static interface EdsTransferOption {
		/// <i>native declaration : line 1054</i>
		public static final int kEdsTransferOption_ByDirectTransfer = 1;
		/// <i>native declaration : line 1055</i>
		public static final int kEdsTransferOption_ByRelease = 2;
		/// <i>native declaration : line 1056</i>
		public static final int kEdsTransferOption_ToDesktop = 256;
	};
	/// enum values
	public static interface EdsAEMode {
		/// <i>native declaration : line 1065</i>
		public static final int kEdsAEMode_Program = 0;
		/// <i>native declaration : line 1066</i>
		public static final int kEdsAEMode_Tv = 1;
		/// <i>native declaration : line 1067</i>
		public static final int kEdsAEMode_Av = 2;
		/// <i>native declaration : line 1068</i>
		public static final int kEdsAEMode_Manual = 3;
		/// <i>native declaration : line 1069</i>
		public static final int kEdsAEMode_Bulb = 4;
		/// <i>native declaration : line 1070</i>
		public static final int kEdsAEMode_A_DEP = 5;
		/// <i>native declaration : line 1071</i>
		public static final int kEdsAEMode_DEP = 6;
		/// <i>native declaration : line 1072</i>
		public static final int kEdsAEMode_Custom = 7;
		/// <i>native declaration : line 1073</i>
		public static final int kEdsAEMode_Lock = 8;
		/// <i>native declaration : line 1074</i>
		public static final int kEdsAEMode_Green = 9;
		/// <i>native declaration : line 1075</i>
		public static final int kEdsAEMode_NightPortrait = 10;
		/// <i>native declaration : line 1076</i>
		public static final int kEdsAEMode_Sports = 11;
		/// <i>native declaration : line 1077</i>
		public static final int kEdsAEMode_Portrait = 12;
		/// <i>native declaration : line 1078</i>
		public static final int kEdsAEMode_Landscape = 13;
		/// <i>native declaration : line 1079</i>
		public static final int kEdsAEMode_Closeup = 14;
		/// <i>native declaration : line 1080</i>
		public static final int kEdsAEMode_FlashOff = 15;
		/// <i>native declaration : line 1081</i>
		public static final int kEdsAEMode_CreativeAuto = 19;
		/// <i>native declaration : line 1082</i>
		public static final int kEdsAEMode_Movie = 20;
		/// <i>native declaration : line 1083</i>
		public static final int kEdsAEMode_PhotoInMovie = 21;
		/// <i>native declaration : line 1084</i>
		public static final int kEdsAEMode_Unknown = -1;
	};
	/// enum values
	public static interface EdsBracket {
		/// <i>native declaration : line 1093</i>
		public static final int kEdsBracket_AEB = 1;
		/// <i>native declaration : line 1094</i>
		public static final int kEdsBracket_ISOB = 2;
		/// <i>native declaration : line 1095</i>
		public static final int kEdsBracket_WBB = 4;
		/// <i>native declaration : line 1096</i>
		public static final int kEdsBracket_FEB = 8;
		/// <i>native declaration : line 1097</i>
		public static final int kEdsBracket_Unknown = -1;
	};
	/// enum values
	public static interface EdsEvfOutputDevice {
		/// <i>native declaration : line 1106</i>
		public static final int kEdsEvfOutputDevice_TFT = 1;
		/// <i>native declaration : line 1107</i>
		public static final int kEdsEvfOutputDevice_PC = 2;
	};
	/// enum values
	public static interface EdsEvfZoom {
		/// <i>native declaration : line 1115</i>
		public static final int kEdsEvfZoom_Fit = 1;
		/// <i>native declaration : line 1116</i>
		public static final int kEdsEvfZoom_x5 = 5;
		/// <i>native declaration : line 1117</i>
		public static final int kEdsEvfZoom_x10 = 10;
	};
	/// enum values
	public static interface EdsEvfAFMode {
		/// <i>native declaration : line 1125</i>
		public static final int Evf_AFMode_Quick = 0;
		/// <i>native declaration : line 1126</i>
		public static final int Evf_AFMode_Live = 1;
		/// <i>native declaration : line 1127</i>
		public static final int Evf_AFMode_LiveFace = 2;
	};
	/// enum values
	public static interface EdsStroboMode {
		/// <i>native declaration : line 1135</i>
		public static final int kEdsStroboModeInternal = 0;
		/// <i>native declaration : line 1136</i>
		public static final int kEdsStroboModeExternalETTL = 1;
		/// <i>native declaration : line 1137</i>
		public static final int kEdsStroboModeExternalATTL = 2;
		/// <i>native declaration : line 1138</i>
		public static final int kEdsStroboModeExternalTTL = 3;
		/// <i>native declaration : line 1139</i>
		public static final int kEdsStroboModeExternalAuto = 4;
		/// <i>native declaration : line 1140</i>
		public static final int kEdsStroboModeExternalManual = 5;
		/// <i>native declaration : line 1141</i>
		public static final int kEdsStroboModeManual = 6;
	};
	/// enum values
	public static interface EdsETTL2Mode {
		/// <i>native declaration : line 1149</i>
		public static final int kEdsETTL2ModeEvaluative = 0;
		/// <i>native declaration : line 1150</i>
		public static final int kEdsETTL2ModeAverage = 1;
	};
	public static final int EDS_ERR_STREAM_SEEK_ERROR = 165;
	public static final int EDS_ERR_INVALID_PARAMETER = 96;
	public static final int kEdsObjectEvent_VolumeInfoChanged = 513;
	public static final int kEdsStateEvent_ShutDownTimerUpdate = 772;
	public static final int EDS_ERR_FILE_NOT_FOUND = 34;
	public static final int EDS_CMP_ID_CLIENT_COMPONENTID = 16777216;
	public static final int kEdsPropID_Bracket = 1035;
	public static final int kEdsPropID_GPSLatitudeRef = 2049;
	public static final int EDS_ERR_INVALID_FN_CALL = 241;
	public static final int kEdsPropID_WhiteBalanceBracket = 1036;
	public static final int EDS_ERR_INCOMPATIBLE_VERSION = 6;
	public static final int kEdsPropID_DriveMode = 1025;
	public static final int EDS_ERR_PROTECTION_VIOLATION = 9;
	public static final int kEdsPropID_Copyright = 1049;
	public static final int kEdsPropID_FocalLength = 1033;
	public static final int EDS_ERR_INVALID_DEVICEPROP_FORMAT = 8219;
	public static final int kEdsPropID_LensName = 1037;
	public static final int EDS_ERR_FILE_DISK_FULL_ERROR = 42;
	public static final int kEdsPropID_DigitalExposure = 261;
	public static final int kEdsPropID_PictureStyle = 276;
	public static final int EDS_ERR_WAIT_TIMEOUT_ERROR = 244;
	public static final int EDS_ERR_INVALID_OBJECTFORMATCODE = 8203;
	public static final int EDS_ERR_TAKE_PICTURE_MOVIE_CROP_NG = 36105;
	public static final int EDS_ERR_INVALID_LENGTH = 100;
	public static final int kEdsPropID_WhiteBalanceShift = 264;
	public static final int kEdsObjectEvent_FolderUpdateItems = 515;
	public static final int EDS_ERR_INVALID_TRANSACTIONID = 8196;
	public static final int kEdsObjectEvent_VolumeAdded = 524;
	public static final int kEdsPropID_Contrast = 265;
	public static final int EDS_ERR_STREAM_READ_ERROR = 167;
	public static final int EDS_ERR_DEVICE_DISK_ERROR = 136;
	public static final int kEdsPropID_FlashMode = 1044;
	public static final int EDS_ERR_SELECTION_UNAVAILABLE = 11;
	public static final int EDS_MAX_NAME = 256;
	public static final int EDS_RESERVED_MASK = 16711680;
	public static final int EDS_CMP_ID_HLSDK_COMPONENTID = 50331648;
	public static final int kEdsStateEvent_JobStatusChanged = 770;
	public static final int kEdsPropID_Evf_Histogram = 1290;
	public static final int EDS_ERR_STREAM_ALREADY_OPEN = 162;
	public static final int EDS_ISSPECIFIC_MASK = -2147483648;
	public static final int kEdsPropID_MyMenu = 14;
	public static final int kEdsObjectEvent_DirItemRemoved = 517;
	public static final int kEdsPropID_ICCProfile = 259;
	public static final int EDS_ERR_FILE_TOO_MANY_OPEN = 33;
	public static final int kEdsPropID_PictureStyleCaption = 512;
	public static final int EDS_ERR_UNEXPECTED_EXCEPTION = 8;
	public static final int EDS_ERR_STI_DEVICE_RELEASE_ERROR = 227;
	public static final int EDS_ERR_TAKE_PICTURE_SILENCE_NG = 36101;
	public static final int kEdsPropID_BatteryQuality = 16;
	public static final int EDS_ERR_FILE_DATA_CORRUPT = 45;
	public static final int kEdsPropID_Evf_OutputDevice = 1280;
	public static final int kEdsPropID_OwnerName = 4;
	public static final int kEdsPropID_Sharpness = 268;
	public static final int EDS_ERR_INVALID_SORT_FN = 102;
	public static final int kEdsPropID_DepthOfField = 1051;
	public static final int EDS_ERR_ENUM_NA = 240;
	public static final int EDS_ERR_STI_UNKNOWN_ERROR = 224;
	public static final int EDS_ERR_INVALID_POINTER = 98;
	public static final int kEdsPropID_WBCoeffs = 770;
	public static final int kEdsPropID_GPSLongitude = 2052;
	public static final int EDS_ERR_DEVICE_INVALID = 130;
	public static final int EDS_ERR_USB_DEVICE_UNLOCK_ERROR = 209;
	public static final int kEdsPropID_Tv = 1030;
	public static final int EDS_ERR_SPECIFICATION_OF_DESTINATION_UNSUPPORTED = 8224;
	public static final int kEdsCameraStatusCommand_EnterDirectTransfer = 2;
	public static final int kEdsPropID_FirmwareVersion = 7;
	public static final int EDS_ERR_DIR_IO_ERROR = 65;
	public static final int EDS_ERR_CAPTURE_ALREADY_TERMINATED = 8216;
	public static final int EDS_ERR_INVALID_ID = 243;
	public static final int kEdsPropID_HDDirectoryStructure = 32;
	public static final int EDS_ERR_FILE_ALREADY_EXISTS = 43;
	public static final int EDS_ERR_DEVICE_MEMORY_FULL = 132;
	public static final int kEdsPropID_GPSLongitudeRef = 2051;
	public static final int EDS_ERR_INVALID_HANDLE = 97;
	public static final int kEdsPropID_Artist = 1048;
	public static final int EDS_ERR_NOT_SUPPORTED = 7;
	public static final int kEdsCameraCommand_DoClickWBEvf = 260;
	public static final int EDS_ERR_INVALID_INDEX = 99;
	public static final int kEdsObjectEvent_DirItemContentChanged = 519;
	public static final int EDS_ERR_INVALID_PARENTOBJECT = 8218;
	public static final int EDS_ERR_DEVICE_NO_DISK = 135;
	public static final int kEdsPropID_Evf_ImagePosition = 1291;
	public static final int kEdsPropID_DateTime = 6;
	public static final int kEdsCameraStatusCommand_UILock = 0;
	public static final int EDS_ERR_STREAM_PERMISSION_ERROR = 169;
	public static final int kEdsPropertyEvent_PropertyChanged = 257;
	public static final int EDS_ERR_DEVICE_NOT_RELEASED = 141;
	public static final int kEdsPropID_MakerName = 5;
	public static final int kEdsObjectEvent_DirItemCreated = 516;
	public static final int EDS_ERR_NO_VALID_OBJECTINFO = 8213;
	public static final int kEdsCameraCommand_ExtendShutDownTimer = 1;
	public static final int kEdsPropID_Av = 1029;
	public static final int EDS_ERR_TAKE_PICTURE_CARD_NG = 36103;
	public static final int EDS_ERR_DEVICE_DIAL_CHANGED = 138;
	public static final int EDS_ERR_DEVICE_BUSY = 129;
	public static final int EDS_ERR_LENS_COVER_CLOSE = 40966;
	public static final int kEdsPropID_ProductName = 2;
	public static final int kEdsCameraCommand_BulbEnd = 3;
	public static final int kEdsPropID_BatteryLevel = 8;
	public static final int kEdsPropID_Orientation = 258;
	public static final int kEdsPropID_FlashCompensation = 1032;
	public static final int EDS_ERR_DEVICE_CF_GATE_CHANGED = 137;
	public static final int EDS_TRANSFER_BLOCK_SIZE = 512;
	public static final int oldif = 0;
	public static final int kEdsPropID_GPSTimeStamp = 2055;
	public static final int EDS_ERR_DEVICEPROP_NOT_SUPPORTED = 8202;
	public static final int kEdsPropID_CFn = 9;
	public static final int kEdsPropID_ColorMatrix = 275;
	public static final int kEdsPropID_NoiseReduction = 1041;
	public static final int EDS_ERR_COMM_PORT_IS_IN_USE = 192;
	public static final int EDS_ERR_LAST_GENERIC_ERROR_PLUS_ONE = 245;
	public static final int kEdsPropID_GPSVersionID = 2048;
	public static final int kEdsPropID_Evf_ColorTemperature = 1283;
	public static final int kEdsPropID_GPSStatus = 2057;
	public static final int EDS_ERR_STREAM_END_OF_STREAM = 172;
	public static final int EDS_ERR_FILE_WRITE_ERROR = 40;
	public static final int EDS_ERR_DIR_NOT_FOUND = 64;
	public static final int kEdsPropID_ToneCurve = 270;
	public static final int kEdsCameraCommand_PressShutterButton = 4;
	public static final int kEdsPropID_Evf_ZoomRect = 1345;
	public static final int EDS_ERR_OK = 0;
	public static final int kEdsPropID_AtCapture_Flag = -2147483648;
	public static final int kEdsPropID_GPSDateStamp = 2077;
	public static final int EDS_ERR_DIR_ENTRY_EXISTS = 67;
	public static final int EDS_ERR_FILE_SEEK_ERROR = 37;
	public static final int EDS_ERR_PROPERTIES_NOT_LOADED = 83;
	public static final int EDS_ERR_SESSION_NOT_OPEN = 8195;
	public static final int kEdsPropID_SaveTo = 11;
	public static final int EDS_ERR_TAKE_PICTURE_CARD_PROTECT_NG = 36104;
	public static final int kEdsPropID_ExposureCompensation = 1031;
	public static final int kEdsPropID_CurrentFolder = 13;
	public static final int kEdsCameraStatusCommand_UIUnLock = 1;
	public static final int EDS_ERR_DEVICE_INTERNAL_ERROR = 133;
	public static final int EDS_ERR_FILE_FORMAT_UNRECOGNIZED = 44;
	public static final int kEdsStateEvent_InternalError = 774;
	public static final int EDS_COMPONENTID_MASK = 2130706432;
	public static final int EDS_ERR_DIR_ENTRY_NOT_FOUND = 66;
	public static final int kEdsCameraCommand_BulbStart = 2;
	public static final int kEdsPropID_ColorTemperature = 263;
	public static final int EDS_ERR_STREAM_BAD_OPTIONS = 171;
	public static final int kEdsObjectEvent_VolumeUpdateItems = 514;
	public static final int EDS_ERR_COMM_BUFFER_FULL = 195;
	public static final int EDS_ERR_COMM_USB_BUS_ERR = 196;
	public static final int kEdsPropID_ColorSpace = 269;
	public static final int kEdsPropID_AFMode = 1028;
	public static final int EDS_ERR_TAKE_PICTURE_AF_NG = 36097;
	public static final int kEdsStateEvent_BulbExposureTime = 784;
	public static final int EDS_ERR_DEVICE_NOT_INSTALLED = 139;
	public static final int kEdsPropID_Evf_WhiteBalance = 1282;
	public static final int EDS_ERR_DEVICE_INVALID_PARAMETER = 134;
	public static final int kEdsPropID_PhotoEffect = 271;
	public static final int kEdsPropID_Evf_DepthOfFieldPreview = 1284;
	public static final int kEdsPropID_Evf_Mode = 1281;
	public static final int kEdsPropID_Evf_FocusAid = 1289;
	public static final int kEdsPropID_FlashOn = 1042;
	public static final int kEdsPropID_ISOBracket = 1040;
	public static final int EDS_ERR_SPECIFICATION_BY_FORMAT_UNSUPPORTED = 8212;
	public static final int kEdsPropID_EFCompensation = 1054;
	public static final int kEdsPropID_PictureStyleDesc = 277;
	public static final int kEdsCameraCommand_DoEvfAf = 258;
	public static final int kEdsPropertyEvent_PropertyDescChanged = 258;
	public static final int kEdsPropID_ISOSpeed = 1026;
	public static final int EDS_ERR_PROPERTIES_MISMATCH = 81;
	public static final int EDS_ERR_STREAM_WRITE_ERROR = 168;
	public static final int EDS_ERR_INTERNAL_ERROR = 2;
	public static final int EDS_ERR_MEM_FREE_FAILED = 4;
	public static final int EDS_ERR_FILE_OPEN_ERROR = 35;
	public static final int kEdsPropID_JpegQuality = 257;
	public static final int kEdsPropID_BodyID = 3;
	public static final int kEdsPropID_Evf_CoordinateSystem = 1344;
	public static final int EDS_ERR_STI_INTERNAL_ERROR = 225;
	public static final int kEdsPropID_AvailableShots = 1034;
	public static final int EDS_ERR_STI_DEVICE_CREATE_ERROR = 226;
	public static final int EDS_ERR_INVALID_CODE_FORMAT = 8214;
	public static final int kEdsStateEvent_AfResult = 777;
	public static final int kEdsStateEvent_All = 768;
	public static final int EDS_ERRORID_MASK = 65535;
	public static final int kEdsPropID_RedEye = 1043;
	public static final int EDS_ERR_UNIMPLEMENTED = 1;
	public static final int EDS_ERR_OPERATION_CANCELLED = 5;
	public static final int kEdsPropID_Evf_ZoomPosition = 1288;
	public static final int kEdsObjectEvent_DirItemRequestTransfer = 520;
	public static final int NULL = 0;
	public static final int EDS_ERR_TRANSACTION_CANCELLED = 8223;
	public static final int kEdsPropID_Evf_Zoom = 1287;
	public static final int kEdsObjectEvent_All = 512;
	public static final int EDS_ERR_STREAM_CLOSE_ERROR = 164;
	public static final int kEdsPropID_FilterEffect = 272;
	public static final int EDS_ERR_INVALID_STRAGEID = 8200;
	public static final int EDS_ERR_MEM_ALLOC_FAILED = 3;
	public static final int kEdsPropID_FocusInfo = 260;
	public static final int EDS_ERR_DEVICE_STAY_AWAKE = 140;
	public static final int EDS_ERR_STREAM_NOT_OPEN = 161;
	public static final int kEdsPropertyEvent_All = 256;
	public static final int kEdsObjectEvent_DirItemCancelTransferDT = 522;
	public static final int EDS_ERR_TAKE_PICTURE_MIRROR_UP_NG = 36099;
	public static final int EDS_ERR_HANDLE_NOT_FOUND = 242;
	public static final int kEdsStateEvent_Shutdown = 769;
	public static final int EDS_ERR_INVALID_DEVICEPROP_VALUE = 8220;
	public static final int kEdsPropID_Evf_HistogramStatus = 1292;
	public static final int kEdsPropID_GPSAltitudeRef = 2053;
	public static final int EDS_ERR_COMM_DEVICE_INCOMPATIBLE = 194;
	public static final int EDS_ERR_DEVICE_NOT_LAUNCHED = 228;
	public static final int kEdsPropID_ImageQuality = 256;
	public static final int EDS_ERR_FILE_TELL_ERROR = 38;
	public static final int EDS_ERR_SESSION_ALREADY_OPEN = 8222;
	public static final int EDS_ERR_DEVICE_NOT_FOUND = 128;
	public static final int EDS_ERR_STREAM_IO_ERROR = 160;
	public static final int EDS_ERR_INVALID_FN_POINTER = 101;
	public static final int FALSE = 0;
	public static final int EDS_ERR_OPERATION_REFUSED = 40965;
	public static final int kEdsPropID_GPSMapDatum = 2066;
	public static final int kEdsObjectEvent_VolumeRemoved = 525;
	public static final int EDS_ERR_SELF_TEST_FAILED = 8209;
	public static final int kEdsPropID_WhiteBalance = 262;
	public static final int kEdsPropID_GPSAltitude = 2054;
	public static final int EDS_ERR_COMM_DISCONNECTED = 193;
	public static final int kEdsObjectEvent_DirItemRequestTransferDT = 521;
	public static final int EDS_ERR_USB_DEVICE_LOCK_ERROR = 208;
	public static final int EDS_CMP_ID_LLSDK_COMPONENTID = 33554432;
	public static final int kEdsPropID_GPSSatellites = 2056;
	public static final int kEdsPropID_AEMode = 1024;
	public static final int kEdsCameraCommand_DriveLensEvf = 259;
	public static final int kEdsCameraStatusCommand_ExitDirectTransfer = 3;
	public static final int kEdsPropID_ETTL2Mode = 279;
	public static final int kEdsPropID_ToningEffect = 273;
	public static final int EDS_ERR_DEVICE_EMERGENCY = 131;
	public static final int kEdsCameraCommand_TakePicture = 0;
	public static final int EDS_ERR_STREAM_TELL_ERROR = 166;
	public static final int kEdsPropID_LensStatus = 1046;
	public static final int EDS_ERR_TAKE_PICTURE_STROBO_CHARGE_NG = 36106;
	public static final int kEdsPropID_ParameterSet = 274;
	public static final int kEdsStateEvent_CaptureError = 773;
	public static final int kEdsPropID_Unknown = 65535;
	public static final int EDS_ERR_PROPERTIES_UNAVAILABLE = 80;
	public static final int kEdsPropID_AEBracket = 1038;
	public static final int EDS_ERR_PARTIAL_DELETION = 8210;
	public static final int EDS_ERR_TAKE_PICTURE_RESERVED = 36098;
	public static final int EDS_ERR_STREAM_COULDNT_BEGIN_THREAD = 170;
	public static final int EDS_ERR_FILE_READ_ERROR = 39;
	public static final int kEdsPropID_ColorTone = 267;
	public static final int kEdsPropID_GPSLatitude = 2050;
	public static final int EDS_ERR_MISSING_SUBCOMPONENT = 10;
	public static final int kEdsPropID_ColorSaturation = 266;
	public static final int kEdsPropID_MeteringMode = 1027;
	public static final int EDS_ERR_FILE_NAMING_NA = 46;
	public static final int kEdsPropID_Linear = 768;
	public static final int EDS_ERR_FILE_IO_ERROR = 32;
	public static final int kEdsPropID_CurrentStorage = 12;
	public static final int kEdsPropID_FEBracket = 1039;
	public static final int EDS_ERR_FILE_PERMISSION_ERROR = 41;
	public static final int kEdsPropID_ClickWBPoint = 769;
	public static final int kEdsStateEvent_WillSoonShutDown = 771;
	public static final int EDS_ERR_TAKE_PICTURE_SENSOR_CLEANING_NG = 36100;
	public static final int TRUE = 1;
	public static final int EDS_ERR_FILE_CLOSE_ERROR = 36;
	public static final int EDS_ERR_INCOMPLETE_TRANSFER = 8199;
	public static final int EDS_ERR_TAKE_PICTURE_NO_CARD_NG = 36102;
	public static final int EDS_ERR_LOW_BATTERY = 41217;
	public static final int EDS_ERR_UNKNOWN_COMMAND = 40961;
	public static final int EDS_ERR_UNKNOWN_VENDOR_CODE = 8215;
	public static final int EDS_ERR_STREAM_OPEN_ERROR = 163;
	public static final int kEdsObjectEvent_DirItemInfoChanged = 518;
	public static final int EDS_ERR_DIR_NOT_EMPTY = 68;
	public static final int EDS_ERR_OBJECT_NOTREADY = 41218;
	public static final int kEdsPropID_Evf_AFMode = 1294;
	/**
	 * -----------------------------------------------------------------------------<br>
	 * EdsProgressCallback<br>
	 * -----------------------------------------------------------------------------
	 */
	public interface EdsProgressCallback extends StdCallCallback {
		NativeLong invoke(NativeLong inPercent, CanonSDK.EdsVoid inContext, IntByReference outCancel);
	};
	/**
	 * -----------------------------------------------------------------------------<br>
	 * EdsCameraAddedHandler<br>
	 * -----------------------------------------------------------------------------
	 */
	public interface EdsCameraAddedHandler extends StdCallCallback {
		NativeLong invoke(CanonSDK.EdsVoid inContext);
	};
	/**
	 * -----------------------------------------------------------------------------<br>
	 * EdsPropertyEventHandler<br>
	 * -----------------------------------------------------------------------------
	 */
	public interface EdsPropertyEventHandler extends StdCallCallback {
		NativeLong invoke(NativeLong inEvent, NativeLong inPropertyID, NativeLong inParam, CanonSDK.EdsVoid inContext);
	};
	/**
	 * -----------------------------------------------------------------------------<br>
	 * EdsObjectEventHandler<br>
	 * -----------------------------------------------------------------------------
	 */
	public interface EdsObjectEventHandler extends StdCallCallback {
		// CHANGED FROM NATIVELONG to ... NATIVELONG!
		NativeLong invoke(NativeLong inEvent, CanonSDK.__EdsObject inRef, CanonSDK.EdsVoid inContext);
	};
	/**
	 * -----------------------------------------------------------------------------<br>
	 * EdsStateEventHandler<br>
	 * -----------------------------------------------------------------------------
	 */
	public interface EdsStateEventHandler extends StdCallCallback {
		NativeLong invoke(NativeLong inEvent, NativeLong inEventData, CanonSDK.EdsVoid inContext);
	};
	/**
	 * Original signature : <code>EdsInitializeSDK()</code><br>
	 * <i>native declaration : line 1488</i>
	 */
	int EdsInitializeSDK();
	/**
	 * Original signature : <code>EdsTerminateSDK()</code><br>
	 * <i>native declaration : line 1505</i>
	 */
	int EdsTerminateSDK();
	/**
	 * Original signature : <code>EdsRetain(EdsBaseRef)</code><br>
	 * <i>native declaration : line 1530</i>
	 */
	int EdsRetain(CanonSDK.__EdsObject inRef);
	/**
	 * Original signature : <code>EdsRelease(EdsBaseRef)</code><br>
	 * <i>native declaration : line 1546</i>
	 */
	int EdsRelease(CanonSDK.__EdsObject inRef);
	/**
	 * Original signature : <code>EdsGetChildCount(EdsBaseRef, EdsUInt32*)</code><br>
	 * <i>native declaration : line 1572</i>
	 */
	int EdsGetChildCount(CanonSDK.__EdsObject inRef, NativeLongByReference outCount);
	/**
	 * Original signature : <code>EdsGetChildAtIndex(EdsBaseRef, EdsInt32, EdsBaseRef*)</code><br>
	 * <i>native declaration : line 1591</i><br>
	 * @deprecated use the safer method {@link #EdsGetChildAtIndex(edsdk.CanonSDK.__EdsObject, com.sun.jna.NativeLong, edsdk.CanonSDK.__EdsObject[])} instead
	 */
	@java.lang.Deprecated 
	int EdsGetChildAtIndex(CanonSDK.__EdsObject inRef, NativeLong inIndex, PointerByReference outRef);
	/**
	 * Original signature : <code>EdsGetChildAtIndex(EdsBaseRef, EdsInt32, EdsBaseRef*)</code><br>
	 * <i>native declaration : line 1591</i>
	 */
	int EdsGetChildAtIndex(CanonSDK.__EdsObject inRef, NativeLong inIndex, CanonSDK.__EdsObject outRef[]);
	/**
	 * Original signature : <code>EdsGetParent(EdsBaseRef, EdsBaseRef*)</code><br>
	 * <i>native declaration : line 1609</i><br>
	 * @deprecated use the safer method {@link #EdsGetParent(edsdk.CanonSDK.__EdsObject, edsdk.CanonSDK.__EdsObject[])} instead
	 */
	@java.lang.Deprecated 
	int EdsGetParent(CanonSDK.__EdsObject inRef, PointerByReference outParentRef);
	/**
	 * Original signature : <code>EdsGetParent(EdsBaseRef, EdsBaseRef*)</code><br>
	 * <i>native declaration : line 1609</i>
	 */
	int EdsGetParent(CanonSDK.__EdsObject inRef, CanonSDK.__EdsObject outParentRef[]);
	/**
	 * Original signature : <code>EdsGetPropertySize(EdsBaseRef, EdsPropertyID, EdsInt32, EdsDataType*, EdsUInt32*)</code><br>
	 * <i>native declaration : line 1643</i><br>
	 * @deprecated use the safer methods {@link #EdsGetPropertySize(edsdk.CanonSDK.__EdsObject, com.sun.jna.NativeLong, com.sun.jna.NativeLong, java.nio.IntBuffer, com.sun.jna.ptr.NativeLongByReference)} and {@link #EdsGetPropertySize(edsdk.CanonSDK.__EdsObject, com.sun.jna.NativeLong, com.sun.jna.NativeLong, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.NativeLongByReference)} instead<br>
	 * @param outDataType @see EdsDataType
	 */
	@java.lang.Deprecated 
	int EdsGetPropertySize(CanonSDK.__EdsObject inRef, NativeLong inPropertyID, NativeLong inParam, IntByReference outDataType, NativeLongByReference outSize);
	/**
	 * Original signature : <code>EdsGetPropertySize(EdsBaseRef, EdsPropertyID, EdsInt32, EdsDataType*, EdsUInt32*)</code><br>
	 * <i>native declaration : line 1643</i>
	 */
	int EdsGetPropertySize(CanonSDK.__EdsObject inRef, NativeLong inPropertyID, NativeLong inParam, IntBuffer outDataType, NativeLongByReference outSize);
	/**
	 * Original signature : <code>EdsGetPropertyData(EdsBaseRef, EdsPropertyID, EdsInt32, EdsUInt32, EdsVoid*)</code><br>
	 * <i>native declaration : line 1669</i>
	 */
	int EdsGetPropertyData(CanonSDK.__EdsObject inRef, NativeLong inPropertyID, NativeLong inParam, NativeLong inPropertySize, CanonSDK.EdsVoid outPropertyData);
	/**
	 * Original signature : <code>EdsSetPropertyData(EdsBaseRef, EdsPropertyID, EdsInt32, EdsUInt32, const EdsVoid*)</code><br>
	 * <i>native declaration : line 1694</i>
	 */
	int EdsSetPropertyData(CanonSDK.__EdsObject inRef, NativeLong inPropertyID, NativeLong inParam, NativeLong inPropertySize, CanonSDK.EdsVoid inPropertyData);
	/**
	 * Original signature : <code>EdsGetPropertyDesc(EdsBaseRef, EdsPropertyID, EdsPropertyDesc*)</code><br>
	 * <i>native declaration : line 1717</i>
	 */
	int EdsGetPropertyDesc(CanonSDK.__EdsObject inRef, NativeLong inPropertyID, edsdk.EdsPropertyDesc outPropertyDesc);
	/**
	 * Original signature : <code>EdsGetCameraList(EdsCameraListRef*)</code><br>
	 * <i>native declaration : line 1744</i><br>
	 * @deprecated use the safer method {@link #EdsGetCameraList(edsdk.CanonSDK.__EdsObject[])} instead
	 */
	@java.lang.Deprecated 
	int EdsGetCameraList(PointerByReference outCameraListRef);
	/**
	 * Original signature : <code>EdsGetCameraList(EdsCameraListRef*)</code><br>
	 * <i>native declaration : line 1744</i>
	 */
	int EdsGetCameraList(CanonSDK.__EdsObject outCameraListRef[]);
	/**
	 * Original signature : <code>EdsGetDeviceInfo(EdsCameraRef, EdsDeviceInfo*)</code><br>
	 * <i>native declaration : line 1773</i>
	 */
	int EdsGetDeviceInfo(CanonSDK.__EdsObject inCameraRef, edsdk.EdsDeviceInfo outDeviceInfo);
	/**
	 * Original signature : <code>EdsOpenSession(EdsCameraRef)</code><br>
	 * <i>native declaration : line 1791</i>
	 */
	int EdsOpenSession(CanonSDK.__EdsObject inCameraRef);
	/**
	 * Original signature : <code>EdsCloseSession(EdsCameraRef)</code><br>
	 * <i>native declaration : line 1807</i>
	 */
	int EdsCloseSession(CanonSDK.__EdsObject inCameraRef);
	/**
	 * Original signature : <code>EdsSendCommand(EdsCameraRef, EdsCameraCommand, EdsInt32)</code><br>
	 * <i>native declaration : line 1826</i>
	 */
	int EdsSendCommand(CanonSDK.__EdsObject inCameraRef, NativeLong inCommand, NativeLong inParam);
	/**
	 * Original signature : <code>EdsSendStatusCommand(EdsCameraRef, EdsCameraStatusCommand, EdsInt32)</code><br>
	 * <i>native declaration : line 1847</i>
	 */
	int EdsSendStatusCommand(CanonSDK.__EdsObject inCameraRef, NativeLong inStatusCommand, NativeLong inParam);
	/**
	 * Original signature : <code>EdsSetCapacity(EdsCameraRef, EdsCapacity)</code><br>
	 * <i>native declaration : line 1878</i>
	 */
	int EdsSetCapacity(CanonSDK.__EdsObject inCameraRef, edsdk.EdsCapacity.ByValue inCapacity);
	/**
	 * Original signature : <code>EdsGetVolumeInfo(EdsVolumeRef, EdsVolumeInfo*)</code><br>
	 * <i>native declaration : line 1904</i>
	 */
	int EdsGetVolumeInfo(CanonSDK.__EdsObject inVolumeRef, edsdk.EdsVolumeInfo outVolumeInfo);
	/**
	 * Original signature : <code>EdsFormatVolume(EdsVolumeRef)</code><br>
	 * <i>native declaration : line 1920</i>
	 */
	int EdsFormatVolume(CanonSDK.__EdsObject inVolumeRef);
	/**
	 * Original signature : <code>EdsGetDirectoryItemInfo(EdsDirectoryItemRef, EdsDirectoryItemInfo*)</code><br>
	 * <i>native declaration : line 1946</i>
	 */
	int EdsGetDirectoryItemInfo(CanonSDK.__EdsObject inDirItemRef, edsdk.EdsDirectoryItemInfo outDirItemInfo);
	/**
	 * Original signature : <code>EdsDeleteDirectoryItem(EdsDirectoryItemRef)</code><br>
	 * <i>native declaration : line 1968</i>
	 */
	int EdsDeleteDirectoryItem(CanonSDK.__EdsObject inDirItemRef);
	/**
	 * Original signature : <code>EdsDownload(EdsDirectoryItemRef, EdsUInt32, EdsStreamRef)</code><br>
	 * <i>native declaration : line 1991</i>
	 */
	int EdsDownload(CanonSDK.__EdsObject inDirItemRef, NativeLong inReadSize, CanonSDK.__EdsObject outStream);
	/**
	 * Original signature : <code>EdsDownloadCancel(EdsDirectoryItemRef)</code><br>
	 * <i>native declaration : line 2011</i>
	 */
	int EdsDownloadCancel(CanonSDK.__EdsObject inDirItemRef);
	/**
	 * Original signature : <code>EdsDownloadComplete(EdsDirectoryItemRef)</code><br>
	 * <i>native declaration : line 2031</i>
	 */
	int EdsDownloadComplete(CanonSDK.__EdsObject inDirItemRef);
	/**
	 * Original signature : <code>EdsDownloadThumbnail(EdsDirectoryItemRef, EdsStreamRef)</code><br>
	 * <i>native declaration : line 2051</i>
	 */
	int EdsDownloadThumbnail(CanonSDK.__EdsObject inDirItemRef, CanonSDK.__EdsObject outStream);
	/**
	 * Original signature : <code>EdsGetAttribute(EdsDirectoryItemRef, EdsFileAttributes*)</code><br>
	 * <i>native declaration : line 2072</i><br>
	 * @deprecated use the safer methods {@link #EdsGetAttribute(edsdk.CanonSDK.__EdsObject, java.nio.IntBuffer)} and {@link #EdsGetAttribute(edsdk.CanonSDK.__EdsObject, com.sun.jna.ptr.IntByReference)} instead<br>
	 * @param outFileAttribute @see EdsFileAttributes
	 */
	@java.lang.Deprecated 
	int EdsGetAttribute(CanonSDK.__EdsObject inDirItemRef, IntByReference outFileAttribute);
	/**
	 * Original signature : <code>EdsGetAttribute(EdsDirectoryItemRef, EdsFileAttributes*)</code><br>
	 * <i>native declaration : line 2072</i>
	 */
	int EdsGetAttribute(CanonSDK.__EdsObject inDirItemRef, IntBuffer outFileAttribute);
	/**
	 * Original signature : <code>EdsSetAttribute(EdsDirectoryItemRef, EdsFileAttributes)</code><br>
	 * <i>native declaration : line 2092</i><br>
	 * @param inFileAttribute @see EdsFileAttributes
	 */
	int EdsSetAttribute(CanonSDK.__EdsObject inDirItemRef, int inFileAttribute);
	/**
	 * Original signature : <code>EdsCreateFileStream(const EdsChar*, EdsFileCreateDisposition, EdsAccess, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2127</i><br>
	 * @deprecated use the safer methods {@link #EdsCreateFileStream(java.nio.ByteBuffer, int, int, edsdk.CanonSDK.__EdsObject[])} and {@link #EdsCreateFileStream(com.sun.jna.Pointer, int, int, edsdk.CanonSDK.__EdsObject[])} instead<br>
	 * @param inCreateDisposition @see EdsFileCreateDisposition<br>
	 * @param inDesiredAccess @see EdsAccess
	 */
	@java.lang.Deprecated 
	int EdsCreateFileStream(Pointer inFileName, int inCreateDisposition, int inDesiredAccess, PointerByReference outStream);
	/**
	 * Original signature : <code>EdsCreateFileStream(const EdsChar*, EdsFileCreateDisposition, EdsAccess, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2127</i><br>
	 * @param inCreateDisposition @see EdsFileCreateDisposition<br>
	 * @param inDesiredAccess @see EdsAccess
	 */
	int EdsCreateFileStream(ByteBuffer inFileName, int inCreateDisposition, int inDesiredAccess, CanonSDK.__EdsObject outStream[]);
	/**
	 * Original signature : <code>EdsCreateFileStream(const EdsChar*, EdsFileCreateDisposition, EdsAccess, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2127</i><br>
	 * @param inCreateDisposition @see EdsFileCreateDisposition<br>
	 * @param inDesiredAccess @see EdsAccess
	 */
	int EdsCreateFileStream(Pointer inFileName, int inCreateDisposition, int inDesiredAccess, CanonSDK.__EdsObject outStream[]);
	/**
	 * Original signature : <code>EdsCreateMemoryStream(EdsUInt32, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2149</i><br>
	 * @deprecated use the safer method {@link #EdsCreateMemoryStream(com.sun.jna.NativeLong, edsdk.CanonSDK.__EdsObject[])} instead
	 */
	@java.lang.Deprecated 
	int EdsCreateMemoryStream(NativeLong inBufferSize, PointerByReference outStream);
	/**
	 * Original signature : <code>EdsCreateMemoryStream(EdsUInt32, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2149</i>
	 */
	int EdsCreateMemoryStream(NativeLong inBufferSize, CanonSDK.__EdsObject outStream[]);
	/**
	 * Original signature : <code>EdsCreateFileStreamEx(const WCHAR*, EdsFileCreateDisposition, EdsAccess, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2173</i><br>
	 * @deprecated use the safer methods {@link #EdsCreateFileStreamEx(short[], int, int, edsdk.CanonSDK.__EdsObject[])} and {@link #EdsCreateFileStreamEx(com.sun.jna.ptr.ShortByReference, int, int, edsdk.CanonSDK.__EdsObject[])} instead<br>
	 * @param inCreateDisposition @see EdsFileCreateDisposition<br>
	 * @param inDesiredAccess @see EdsAccess
	 */
	@java.lang.Deprecated 
	int EdsCreateFileStreamEx(ShortByReference inFileName, int inCreateDisposition, int inDesiredAccess, PointerByReference outStream);
	/**
	 * Original signature : <code>EdsCreateFileStreamEx(const WCHAR*, EdsFileCreateDisposition, EdsAccess, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2173</i><br>
	 * @param inCreateDisposition @see EdsFileCreateDisposition<br>
	 * @param inDesiredAccess @see EdsAccess
	 */
	int EdsCreateFileStreamEx(short inFileName[], int inCreateDisposition, int inDesiredAccess, CanonSDK.__EdsObject outStream[]);
	/**
	 * Original signature : <code>EdsCreateFileStreamEx(const WCHAR*, EdsFileCreateDisposition, EdsAccess, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2173</i><br>
	 * @param inCreateDisposition @see EdsFileCreateDisposition<br>
	 * @param inDesiredAccess @see EdsAccess
	 */
	int EdsCreateFileStreamEx(ShortByReference inFileName, int inCreateDisposition, int inDesiredAccess, CanonSDK.__EdsObject outStream[]);
	/**
	 * Original signature : <code>EdsCreateMemoryStreamFromPointer(EdsVoid*, EdsUInt32, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2201</i><br>
	 * @deprecated use the safer method {@link #EdsCreateMemoryStreamFromPointer(edsdk.CanonSDK.EdsVoid, com.sun.jna.NativeLong, edsdk.CanonSDK.__EdsObject[])} instead
	 */
	@java.lang.Deprecated 
	int EdsCreateMemoryStreamFromPointer(CanonSDK.EdsVoid inUserBuffer, NativeLong inBufferSize, PointerByReference outStream);
	/**
	 * Original signature : <code>EdsCreateMemoryStreamFromPointer(EdsVoid*, EdsUInt32, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2201</i>
	 */
	int EdsCreateMemoryStreamFromPointer(CanonSDK.EdsVoid inUserBuffer, NativeLong inBufferSize, CanonSDK.__EdsObject outStream[]);
	/**
	 * Original signature : <code>EdsGetPointer(EdsStreamRef, EdsVoid**)</code><br>
	 * <i>native declaration : line 2228</i>
	 */
	int EdsGetPointer(CanonSDK.__EdsObject inStream, PointerByReference outPointer);
	/**
	 * Original signature : <code>EdsRead(EdsStreamRef, EdsUInt32, EdsVoid*, EdsUInt32*)</code><br>
	 * <i>native declaration : line 2251</i>
	 */
	int EdsRead(CanonSDK.__EdsObject inStreamRef, NativeLong inReadSize, CanonSDK.EdsVoid outBuffer, NativeLongByReference outReadSize);
	/**
	 * Original signature : <code>EdsWrite(EdsStreamRef, EdsUInt32, const EdsVoid*, EdsUInt32*)</code><br>
	 * <i>native declaration : line 2275</i>
	 */
	int EdsWrite(CanonSDK.__EdsObject inStreamRef, NativeLong inWriteSize, CanonSDK.EdsVoid inBuffer, NativeLongByReference outWrittenSize);
	/**
	 * Original signature : <code>EdsSeek(EdsStreamRef, EdsInt32, EdsSeekOrigin)</code><br>
	 * <i>native declaration : line 2304</i><br>
	 * @param inSeekOrigin @see EdsSeekOrigin
	 */
	int EdsSeek(CanonSDK.__EdsObject inStreamRef, NativeLong inSeekOffset, int inSeekOrigin);
	/**
	 * Original signature : <code>EdsGetPosition(EdsStreamRef, EdsUInt32*)</code><br>
	 * <i>native declaration : line 2324</i>
	 */
	int EdsGetPosition(CanonSDK.__EdsObject inStreamRef, NativeLongByReference outPosition);
	/**
	 * Original signature : <code>EdsGetLength(EdsStreamRef, EdsUInt32*)</code><br>
	 * <i>native declaration : line 2342</i>
	 */
	int EdsGetLength(CanonSDK.__EdsObject inStreamRef, NativeLongByReference outLength);
	/**
	 * Original signature : <code>EdsCopyData(EdsStreamRef, EdsUInt32, EdsStreamRef)</code><br>
	 * <i>native declaration : line 2366</i>
	 */
	int EdsCopyData(CanonSDK.__EdsObject inStreamRef, NativeLong inWriteSize, CanonSDK.__EdsObject outStreamRef);
	/**
	 * Original signature : <code>EdsSetProgressCallback(EdsBaseRef, EdsProgressCallback, EdsProgressOption, EdsVoid*)</code><br>
	 * <i>native declaration : line 2402</i><br>
	 * @param inProgressOption @see EdsProgressOption
	 */
	int EdsSetProgressCallback(CanonSDK.__EdsObject inRef, CanonSDK.EdsProgressCallback inProgressCallback, int inProgressOption, CanonSDK.EdsVoid inContext);
	/**
	 * Original signature : <code>EdsCreateImageRef(EdsStreamRef, EdsImageRef*)</code><br>
	 * <i>native declaration : line 2438</i><br>
	 * @deprecated use the safer method {@link #EdsCreateImageRef(edsdk.CanonSDK.__EdsObject, edsdk.CanonSDK.__EdsObject[])} instead
	 */
	@java.lang.Deprecated 
	int EdsCreateImageRef(CanonSDK.__EdsObject inStreamRef, PointerByReference outImageRef);
	/**
	 * Original signature : <code>EdsCreateImageRef(EdsStreamRef, EdsImageRef*)</code><br>
	 * <i>native declaration : line 2438</i>
	 */
	int EdsCreateImageRef(CanonSDK.__EdsObject inStreamRef, CanonSDK.__EdsObject outImageRef[]);
	/**
	 * Original signature : <code>EdsGetImageInfo(EdsImageRef, EdsImageSource, EdsImageInfo*)</code><br>
	 * <i>native declaration : line 2473</i><br>
	 * @param inImageSource @see EdsImageSource
	 */
	int EdsGetImageInfo(CanonSDK.__EdsObject inImageRef, int inImageSource, edsdk.EdsImageInfo outImageInfo);
	/**
	 * Original signature : <code>EdsGetImage(EdsImageRef, EdsImageSource, EdsTargetImageType, EdsRect, EdsSize, EdsStreamRef)</code><br>
	 * <i>native declaration : line 2518</i><br>
	 * @param inImageSource @see EdsImageSource<br>
	 * @param inImageType @see EdsTargetImageType
	 */
	int EdsGetImage(CanonSDK.__EdsObject inImageRef, int inImageSource, int inImageType, edsdk.EdsRect.ByValue inSrcRect, edsdk.EdsSize.ByValue inDstSize, CanonSDK.__EdsObject outStreamRef);
	/**
	 * Original signature : <code>EdsSaveImage(EdsImageRef, EdsTargetImageType, EdsSaveImageSetting, EdsStreamRef)</code><br>
	 * <i>native declaration : line 2551</i><br>
	 * @param inImageType @see EdsTargetImageType
	 */
	int EdsSaveImage(CanonSDK.__EdsObject inImageRef, int inImageType, edsdk.EdsSaveImageSetting.ByValue inSaveSetting, CanonSDK.__EdsObject outStreamRef);
	/**
	 * Original signature : <code>EdsCacheImage(EdsImageRef, EdsBool)</code><br>
	 * <i>native declaration : line 2577</i>
	 */
	int EdsCacheImage(CanonSDK.__EdsObject inImageRef, int inUseCache);
	/**
	 * Original signature : <code>EdsReflectImageProperty(EdsImageRef)</code><br>
	 * <i>native declaration : line 2594</i>
	 */
	int EdsReflectImageProperty(CanonSDK.__EdsObject inImageRef);
	/**
	 * -----------------------------------------------------------------------------<br>
	 * //<br>
	 * //  Function:   EdsCreateEvfImageRef<br>
	 * //  Description:<br>
	 * //       Creates an object used to get the live view image data set.<br>
	 * //<br>
	 * //  Parameters:<br>
	 * //      In:     inStreamRef - The stream reference which opened to get EVF JPEG image.<br>
	 * //      Out:    outEvfImageRef - The EVFData reference.<br>
	 * //<br>
	 * //  Returns:    Any of the sdk errors.<br>
	 * -----------------------------------------------------------------------------<br>
	 * Original signature : <code>EdsError EdsCreateEvfImageRef(EdsStreamRef, EdsEvfImageRef*)</code><br>
	 * <i>native declaration : line 2610</i><br>
	 * @deprecated use the safer method {@link #EdsCreateEvfImageRef(edsdk.CanonSDK.__EdsObject, edsdk.CanonSDK.__EdsObject[])} instead
	 */
	@java.lang.Deprecated 
	NativeLong EdsCreateEvfImageRef(CanonSDK.__EdsObject inStreamRef, PointerByReference outEvfImageRef);
	/**
	 * -----------------------------------------------------------------------------<br>
	 * //<br>
	 * //  Function:   EdsCreateEvfImageRef<br>
	 * //  Description:<br>
	 * //       Creates an object used to get the live view image data set.<br>
	 * //<br>
	 * //  Parameters:<br>
	 * //      In:     inStreamRef - The stream reference which opened to get EVF JPEG image.<br>
	 * //      Out:    outEvfImageRef - The EVFData reference.<br>
	 * //<br>
	 * //  Returns:    Any of the sdk errors.<br>
	 * -----------------------------------------------------------------------------<br>
	 * Original signature : <code>EdsError EdsCreateEvfImageRef(EdsStreamRef, EdsEvfImageRef*)</code><br>
	 * <i>native declaration : line 2610</i>
	 */
	NativeLong EdsCreateEvfImageRef(CanonSDK.__EdsObject inStreamRef, CanonSDK.__EdsObject outEvfImageRef[]);
	/**
	 * -----------------------------------------------------------------------------<br>
	 * //<br>
	 * //  Function:   EdsDownloadEvfImage<br>
	 * //  Description:<br>
	 * //		Downloads the live view image data set for a camera currently in live view mode.<br>
	 * //		Live view can be started by using the property ID:kEdsPropertyID_Evf_OutputDevice and<br>
	 * //		data:EdsOutputDevice_PC to call EdsSetPropertyData.<br>
	 * //		In addition to image data, information such as zoom, focus position, and histogram data<br>
	 * //		is included in the image data set. Image data is saved in a stream maintained by EdsEvfImageRef.<br>
	 * //		EdsGetPropertyData can be used to get information such as the zoom, focus position, etc.<br>
	 * //		Although the information of the zoom and focus position can be obtained from EdsEvfImageRef,<br>
	 * //		settings are applied to EdsCameraRef.<br>
	 * //<br>
	 * //  Parameters:<br>
	 * //      In:     inCameraRef - The Camera reference.<br>
	 * //      In:     inEvfImageRef - The EVFData reference.<br>
	 * //<br>
	 * //  Returns:    Any of the sdk errors.<br>
	 * -----------------------------------------------------------------------------<br>
	 * Original signature : <code>EdsError EdsDownloadEvfImage(EdsCameraRef, EdsEvfImageRef)</code><br>
	 * <i>native declaration : line 2635</i>
	 */
	NativeLong EdsDownloadEvfImage(CanonSDK.__EdsObject inCameraRef, CanonSDK.__EdsObject inEvfImageRef);
	/**
	 * Original signature : <code>EdsSetCameraAddedHandler(EdsCameraAddedHandler, EdsVoid*)</code><br>
	 * <i>native declaration : line 2665</i>
	 */
	int EdsSetCameraAddedHandler(CanonSDK.EdsCameraAddedHandler inCameraAddedHandler, CanonSDK.EdsVoid inContext);
	/**
	 * Original signature : <code>EdsSetPropertyEventHandler(EdsCameraRef, EdsPropertyEvent, EdsPropertyEventHandler, EdsVoid*)</code><br>
	 * <i>native declaration : line 2690</i>
	 */
	int EdsSetPropertyEventHandler(CanonSDK.__EdsObject inCameraRef, NativeLong inEvnet, CanonSDK.EdsPropertyEventHandler inPropertyEventHandler, CanonSDK.EdsVoid inContext);
	/**
	 * Original signature : <code>EdsSetObjectEventHandler(EdsCameraRef, EdsObjectEvent, EdsObjectEventHandler, EdsVoid*)</code><br>
	 * <i>native declaration : line 2719</i>
	 */
	int EdsSetObjectEventHandler(CanonSDK.__EdsObject inCameraRef, NativeLong inEvnet, CanonSDK.EdsObjectEventHandler inObjectEventHandler, CanonSDK.EdsVoid inContext);
	/**
	 * Original signature : <code>EdsSetCameraStateEventHandler(EdsCameraRef, EdsStateEvent, EdsStateEventHandler, EdsVoid*)</code><br>
	 * <i>native declaration : line 2747</i>
	 */
	int EdsSetCameraStateEventHandler(CanonSDK.__EdsObject inCameraRef, NativeLong inEvnet, CanonSDK.EdsStateEventHandler inStateEventHandler, CanonSDK.EdsVoid inContext);
	/**
	 * Original signature : <code>EdsCreateStream(EdsIStream*, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2755</i><br>
	 * @deprecated use the safer method {@link #EdsCreateStream(edsdk.EdsIStream, edsdk.CanonSDK.__EdsObject[])} instead
	 */
	@java.lang.Deprecated 
	int EdsCreateStream(edsdk.EdsIStream inStream, PointerByReference outStreamRef);
	/**
	 * Original signature : <code>EdsCreateStream(EdsIStream*, EdsStreamRef*)</code><br>
	 * <i>native declaration : line 2755</i>
	 */
	int EdsCreateStream(edsdk.EdsIStream inStream, CanonSDK.__EdsObject outStreamRef[]);
	/**
	 * Original signature : <code>EdsGetEvent()</code><br>
	 * <i>native declaration : line 2772</i>
	 */
	int EdsGetEvent();
	/// Pointer to unknown (opaque) type
	public static class EdsVoid extends PointerType {
		public EdsVoid(Pointer address) {
			super(address);
		}
		public EdsVoid() {
			super();
		}
	};
	/// Pointer to unknown (opaque) type
	public static class __EdsObject extends PointerType {
		public __EdsObject(Pointer address) {
			super(address);
		}
		public __EdsObject() {
			super();
		}
	};
}
