package edsdk;
import com.sun.jna.NativeLong;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EdsDirectoryItemInfo extends Structure {
	/// C type : EdsUInt32
	public NativeLong size;
	/// C type : EdsBool
	public int isFolder;
	/// C type : EdsUInt32
	public NativeLong groupID;
	/// C type : EdsUInt32
	public NativeLong option;
	/// C type : EdsChar[256]
	public byte[] szFileName = new byte[(256)];
	public EdsDirectoryItemInfo() {
		super();
	}
	/**
	 * @param size C type : EdsUInt32<br>
	 * @param isFolder C type : EdsBool<br>
	 * @param groupID C type : EdsUInt32<br>
	 * @param option C type : EdsUInt32<br>
	 * @param szFileName C type : EdsChar[256]
	 */
	public EdsDirectoryItemInfo(NativeLong size, int isFolder, NativeLong groupID, NativeLong option, byte szFileName[]) {
		super();
		this.size = size;
		this.isFolder = isFolder;
		this.groupID = groupID;
		this.option = option;
		if (szFileName.length != this.szFileName.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.szFileName = szFileName;
	}
	protected ByReference newByReference() {
		ByReference s = new ByReference();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected ByValue newByValue() {
		ByValue s = new ByValue();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected EdsDirectoryItemInfo newInstance() {
		EdsDirectoryItemInfo s = new EdsDirectoryItemInfo();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	public static class ByReference extends EdsDirectoryItemInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends EdsDirectoryItemInfo implements Structure.ByValue {
		
	};
}
