package edsdk;
import com.sun.jna.NativeLong;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EdsFocusPoint extends Structure {
	/// C type : EdsUInt32
	public NativeLong valid;
	/// C type : EdsUInt32
	public NativeLong selected;
	/// C type : EdsUInt32
	public NativeLong justFocus;
	/// C type : EdsRect
	public edsdk.EdsRect rect;
	/// C type : EdsUInt32
	public NativeLong reserved;
	public EdsFocusPoint() {
		super();
	}
	/**
	 * @param valid C type : EdsUInt32<br>
	 * @param selected C type : EdsUInt32<br>
	 * @param justFocus C type : EdsUInt32<br>
	 * @param rect C type : EdsRect<br>
	 * @param reserved C type : EdsUInt32
	 */
	public EdsFocusPoint(NativeLong valid, NativeLong selected, NativeLong justFocus, edsdk.EdsRect rect, NativeLong reserved) {
		super();
		this.valid = valid;
		this.selected = selected;
		this.justFocus = justFocus;
		this.rect = rect;
		this.reserved = reserved;
	}
	protected ByReference newByReference() {
		ByReference s = new ByReference();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected ByValue newByValue() {
		ByValue s = new ByValue();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected EdsFocusPoint newInstance() {
		EdsFocusPoint s = new EdsFocusPoint();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	public static class ByReference extends EdsFocusPoint implements Structure.ByReference {
		
	};
	public static class ByValue extends EdsFocusPoint implements Structure.ByValue {
		
	};
}
