package edsdk;
import com.sun.jna.NativeLong;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EdsPoint extends Structure {
	/// C type : EdsInt32
	public NativeLong x;
	/// C type : EdsInt32
	public NativeLong y;
	public EdsPoint() {
		super();
	}
	/**
	 * @param x C type : EdsInt32<br>
	 * @param y C type : EdsInt32
	 */
	public EdsPoint(NativeLong x, NativeLong y) {
		super();
		this.x = x;
		this.y = y;
	}
	protected ByReference newByReference() {
		ByReference s = new ByReference();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected ByValue newByValue() {
		ByValue s = new ByValue();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected EdsPoint newInstance() {
		EdsPoint s = new EdsPoint();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	public static class ByReference extends EdsPoint implements Structure.ByReference {
		
	};
	public static class ByValue extends EdsPoint implements Structure.ByValue {
		
	};
}
