package edsdk;
import com.sun.jna.NativeLong;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EdsPropertyDesc extends Structure {
	/// C type : EdsInt32
	public NativeLong form;
	/// C type : EdsInt32
	public NativeLong access;
	/// C type : EdsInt32
	public NativeLong numElements;
	/// C type : EdsInt32[128]
	public NativeLong[] propDesc = new NativeLong[(128)];
	public EdsPropertyDesc() {
		super();
	}
	/**
	 * @param form C type : EdsInt32<br>
	 * @param access C type : EdsInt32<br>
	 * @param numElements C type : EdsInt32<br>
	 * @param propDesc C type : EdsInt32[128]
	 */
	public EdsPropertyDesc(NativeLong form, NativeLong access, NativeLong numElements, NativeLong propDesc[]) {
		super();
		this.form = form;
		this.access = access;
		this.numElements = numElements;
		if (propDesc.length != this.propDesc.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.propDesc = propDesc;
	}
	protected ByReference newByReference() {
		ByReference s = new ByReference();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected ByValue newByValue() {
		ByValue s = new ByValue();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected EdsPropertyDesc newInstance() {
		EdsPropertyDesc s = new EdsPropertyDesc();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	public static class ByReference extends EdsPropertyDesc implements Structure.ByReference {
		
	};
	public static class ByValue extends EdsPropertyDesc implements Structure.ByValue {
		
	};
}
