package edsdk;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EdsRect extends Structure {
	/// C type : EdsPoint
	public edsdk.EdsPoint point;
	/// C type : EdsSize
	public edsdk.EdsSize size;
	public EdsRect() {
		super();
	}
	/**
	 * @param point C type : EdsPoint<br>
	 * @param size C type : EdsSize
	 */
	public EdsRect(edsdk.EdsPoint point, edsdk.EdsSize size) {
		super();
		this.point = point;
		this.size = size;
	}
	protected ByReference newByReference() {
		ByReference s = new ByReference();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected ByValue newByValue() {
		ByValue s = new ByValue();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected EdsRect newInstance() {
		EdsRect s = new EdsRect();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	public static class ByReference extends EdsRect implements Structure.ByReference {
		
	};
	public static class ByValue extends EdsRect implements Structure.ByValue {
		
	};
}
