package edsdk;
import com.sun.jna.NativeLong;
import com.sun.jna.Structure;

import edsdk.CanonSDK.__EdsObject;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EdsSaveImageSetting extends Structure {
	/// C type : EdsUInt32
	public NativeLong JPEGQuality;
	/// C type : EdsStreamRef
	public __EdsObject iccProfileStream;
	/// C type : EdsUInt32
	public NativeLong reserved;
	public EdsSaveImageSetting() {
		super();
	}
	/**
	 * @param JPEGQuality C type : EdsUInt32<br>
	 * @param iccProfileStream C type : EdsStreamRef<br>
	 * @param reserved C type : EdsUInt32
	 */
	public EdsSaveImageSetting(NativeLong JPEGQuality, __EdsObject iccProfileStream, NativeLong reserved) {
		super();
		this.JPEGQuality = JPEGQuality;
		this.iccProfileStream = iccProfileStream;
		this.reserved = reserved;
	}
	protected ByReference newByReference() {
		ByReference s = new ByReference();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected ByValue newByValue() {
		ByValue s = new ByValue();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected EdsSaveImageSetting newInstance() {
		EdsSaveImageSetting s = new EdsSaveImageSetting();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	public static class ByReference extends EdsSaveImageSetting implements Structure.ByReference {
		
	};
	public static class ByValue extends EdsSaveImageSetting implements Structure.ByValue {
		
	};
}
