package edsdk;
import com.sun.jna.NativeLong;
import com.sun.jna.Structure;
/**
 * <i>native declaration : canonsdk-2.9\Windows\EDSDK\Header\EDSDKTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EdsSize extends Structure {
	/// C type : EdsInt32
	public NativeLong width;
	/// C type : EdsInt32
	public NativeLong height;
	public EdsSize() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"width", "height"});
	}
	/**
	 * @param width C type : EdsInt32<br>
	 * @param height C type : EdsInt32
	 */
	public EdsSize(NativeLong width, NativeLong height) {
		super();
		this.width = width;
		this.height = height;
		initFieldOrder();
	}
	public static class ByReference extends EdsSize implements Structure.ByReference {
		
	};
	public static class ByValue extends EdsSize implements Structure.ByValue {
		
	};
}
