package edsdk;
import com.sun.jna.NativeLong;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EdsSize extends Structure {
	/// C type : EdsInt32
	public NativeLong width;
	/// C type : EdsInt32
	public NativeLong height;
	public EdsSize() {
		super();
	}
	/**
	 * @param width C type : EdsInt32<br>
	 * @param height C type : EdsInt32
	 */
	public EdsSize(NativeLong width, NativeLong height) {
		super();
		this.width = width;
		this.height = height;
	}
	protected ByReference newByReference() {
		ByReference s = new ByReference();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected ByValue newByValue() {
		ByValue s = new ByValue();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	protected EdsSize newInstance() {
		EdsSize s = new EdsSize();
		s.useMemory(getPointer());
		write();
		s.read();
		return s;
	}
	public static class ByReference extends EdsSize implements Structure.ByReference {
		
	};
	public static class ByValue extends EdsSize implements Structure.ByValue {
		
	};
}
